import { randomUUID } from 'node:crypto';
import { getPrisma } from '../../db/prisma';
import { AppError } from '../../errors/app-error';
import { enqueue } from '../../integrations/queues';
import { createStorageKey, getResumeStorage } from '../../integrations/storage/resume-storage';
import { resumeProcessingQueue } from './resume.queue';
import { validateResumeUpload, ALLOWED_RESUME_TYPES } from './resume-upload';

function publicVersion(version: any) { return { id: version.id, version: version.version, originalFilename: version.originalFilename, mimeType: version.mimeType, fileSize: Number(version.fileSize), status: version.status, parsedData: version.parsedData, parsingMetadata: version.parsingMetadata, failureCode: version.failureCode, createdAt: version.createdAt, updatedAt: version.updatedAt }; }
async function profileId(userId: string) { const profile = await getPrisma().candidateProfile.findUnique({ where: { userId }, select: { id: true } }); if (!profile) throw new AppError('PROFILE_NOT_FOUND', 404, 'Candidate profile not found'); return profile.id; }
async function assertResume(userId: string, resumeId: string) { const profile = await profileId(userId); const resume = await getPrisma().resume.findFirst({ where: { id: resumeId, profileId: profile }, include: { versions: { orderBy: { version: 'desc' }, take: 1 } } }); if (!resume) throw new AppError('RESUME_NOT_FOUND', 404, 'Resume not found'); return resume; }
async function createVersion(userId: string, resumeId: string, file: Express.Multer.File) {
  const resume = await assertResume(userId, resumeId); validateResumeUpload(file); const latest = resume.versions[0]?.version ?? 0;
  const version = await getPrisma().resumeVersion.create({ data: { resumeId, version: latest + 1, originalFilename: file.originalname, mimeType: file.mimetype, storageKey: `pending/${randomUUID()}`, fileSize: BigInt(file.size), status: 'UPLOADED' } });
  try { const storageKey = createStorageKey(resumeId, version.id, ALLOWED_RESUME_TYPES.get(file.mimetype)!); await getResumeStorage().put(storageKey, file.buffer); const updated = await getPrisma().resumeVersion.update({ where: { id: version.id }, data: { storageKey } }); await enqueue(resumeProcessingQueue(), 'resume.process', { resumeVersionId: updated.id }); return publicVersion(updated); }
  catch (error) { await getPrisma().resumeVersion.update({ where: { id: version.id }, data: { status: 'FAILED', failureCode: 'UPLOAD_FAILED' } }).catch(() => undefined); throw error; }
}
export async function createResume(userId: string, data: { name: string; targetRole?: string | null }, file: Express.Multer.File) { validateResumeUpload(file); const profile = await profileId(userId); const db = getPrisma(); const resume = await db.resume.create({ data: { profileId: profile, name: data.name, targetRole: data.targetRole ?? null } }); try { const version = await db.resumeVersion.create({ data: { resumeId: resume.id, version: 1, originalFilename: file.originalname, mimeType: file.mimetype, storageKey: `pending/${randomUUID()}`, fileSize: BigInt(file.size), status: 'UPLOADED' } }); const storageKey = createStorageKey(resume.id, version.id, ALLOWED_RESUME_TYPES.get(file.mimetype)!); await getResumeStorage().put(storageKey, file.buffer); const saved = await db.resumeVersion.update({ where: { id: version.id }, data: { storageKey } }); await enqueue(resumeProcessingQueue(), 'resume.process', { resumeVersionId: saved.id }); return { id: resume.id, name: resume.name, targetRole: resume.targetRole, isDefault: resume.isDefault, latestVersion: publicVersion(saved), createdAt: resume.createdAt, updatedAt: resume.updatedAt }; } catch (error) { await db.resume.delete({ where: { id: resume.id } }).catch(() => undefined); throw error; } }
export async function listResumes(userId: string) { const profile = await profileId(userId); const resumes = await getPrisma().resume.findMany({ where: { profileId: profile }, include: { versions: { orderBy: { version: 'desc' }, take: 1 } }, orderBy: { updatedAt: 'desc' } }); return resumes.map((r) => ({ id: r.id, name: r.name, targetRole: r.targetRole, isDefault: r.isDefault, latestVersion: r.versions[0] ? publicVersion(r.versions[0]) : null, createdAt: r.createdAt, updatedAt: r.updatedAt })); }
export async function getResume(userId: string, resumeId: string) { const r = await assertResume(userId, resumeId); return { id: r.id, name: r.name, targetRole: r.targetRole, isDefault: r.isDefault, latestVersion: r.versions[0] ? publicVersion(r.versions[0]) : null, createdAt: r.createdAt, updatedAt: r.updatedAt }; }
export async function updateResume(userId: string, resumeId: string, data: { name?: string; targetRole?: string | null; isDefault?: boolean }) { const r = await assertResume(userId, resumeId); const updated = await getPrisma().$transaction(async (tx) => { if (data.isDefault) await tx.resume.updateMany({ where: { profileId: r.profileId, isDefault: true, id: { not: resumeId } }, data: { isDefault: false } }); return tx.resume.update({ where: { id: resumeId }, data }); }); return { ...updated, latestVersion: (await getResume(userId, resumeId)).latestVersion }; }
export async function deleteResume(userId: string, resumeId: string) { const r = await assertResume(userId, resumeId); const keys = r.versions.map((v) => v.storageKey); await getPrisma().resume.delete({ where: { id: r.id } }); for (const key of keys) { try { await getResumeStorage().delete(key); } catch {} } }
export async function listVersions(userId: string, resumeId: string) { await assertResume(userId, resumeId); const versions = await getPrisma().resumeVersion.findMany({ where: { resumeId }, orderBy: { version: 'desc' } }); return versions.map(publicVersion); }
export async function getVersion(userId: string, resumeId: string, versionId: string) { await assertResume(userId, resumeId); const version = await getPrisma().resumeVersion.findFirst({ where: { id: versionId, resumeId } }); if (!version) throw new AppError('RESUME_VERSION_NOT_FOUND', 404, 'Resume version not found'); return publicVersion(version); }
export async function createResumeVersion(userId: string, resumeId: string, file: Express.Multer.File) { return createVersion(userId, resumeId, file); }
export async function deleteVersion(userId: string, resumeId: string, versionId: string) { await assertResume(userId, resumeId); const version = await getPrisma().resumeVersion.findFirst({ where: { id: versionId, resumeId } }); if (!version) throw new AppError('RESUME_VERSION_NOT_FOUND', 404, 'Resume version not found'); const count = await getPrisma().resumeVersion.count({ where: { resumeId } }); if (count <= 1) throw new AppError('LAST_RESUME_VERSION', 409, 'A resume must retain at least one version'); await getPrisma().resumeVersion.delete({ where: { id: versionId } }); try { await getResumeStorage().delete(version.storageKey); } catch {} }
export async function applyParsedSelection(userId: string, resumeId: string, versionId: string, data: { personal?: { fullName?: string; location?: string; websiteUrl?: string | null }; skills?: string[] }) { const profile = await getPrisma().candidateProfile.findUnique({ where: { userId }, select: { id: true } }); if (!profile) throw new AppError('PROFILE_NOT_FOUND', 404, 'Candidate profile not found'); const version = await getPrisma().resumeVersion.findFirst({ where: { id: versionId, resumeId, resume: { profileId: profile.id } }, select: { id: true, parsedData: true } }); if (!version) throw new AppError('RESUME_VERSION_NOT_FOUND', 404, 'Resume version not found'); if (!version.parsedData) throw new AppError('PARSED_DATA_NOT_AVAILABLE', 409, 'Parsed resume data is not available yet'); await getPrisma().$transaction(async (tx) => { if (data.personal) await tx.candidateProfile.update({ where: { id: profile.id }, data: data.personal }); for (const name of data.skills ?? []) { const normalized = name.trim().toLowerCase(); const skill = await tx.skill.upsert({ where: { name: normalized }, update: {}, create: { name: normalized } }); await tx.candidateSkill.upsert({ where: { profileId_skillId: { profileId: profile.id, skillId: skill.id } }, update: {}, create: { profileId: profile.id, skillId: skill.id } }); } }); return { applied: { personal: Boolean(data.personal), skills: data.skills?.length ?? 0 } }; }
