import { Router } from 'express';
import { z } from 'zod';
import { requireAuth } from '../auth/auth.middleware';
import { validate } from '../../middleware/validate';
import { resumeFileUpload } from './resume-upload.middleware';
import { applyParsed, createResume, createVersion, deleteResume, deleteVersion, getParsed, getResume, getVersion, listResumes, listVersions, updateResume } from './resume.controller';
const idParams = z.object({ id: z.string().uuid() });
const versionParams = z.object({ id: z.string().uuid(), versionId: z.string().uuid() });
const empty = z.object({}).strict();
const metadata = z.object({ name: z.string().trim().min(1).max(160), targetRole: z.string().trim().max(160).optional().nullable() });
const update = z.object({ name: z.string().trim().min(1).max(160).optional(), targetRole: z.string().trim().max(160).optional().nullable(), isDefault: z.boolean().optional() }).refine((d) => Object.keys(d).length > 0);
const apply = z.object({ personal: z.object({ fullName: z.string().trim().max(200).optional(), location: z.string().trim().max(200).optional(), websiteUrl: z.string().url().max(500).optional().nullable() }).optional(), skills: z.array(z.string().trim().min(1).max(100)).max(100).optional() }).refine((d) => Boolean(d.personal || d.skills));
const router = Router();
router.use(requireAuth);
router.post('/', resumeFileUpload(), validate(z.object({ body: metadata, params: z.object({}), query: z.object({}) })), createResume);
router.get('/', validate(z.object({ body: empty, params: z.object({}), query: z.object({}) })), listResumes);
router.get('/:id', validate(z.object({ body: empty, params: idParams, query: z.object({}) })), getResume);
router.patch('/:id', validate(z.object({ body: update, params: idParams, query: z.object({}) })), updateResume);
router.delete('/:id', validate(z.object({ body: empty, params: idParams, query: z.object({}) })), deleteResume);
router.get('/:id/versions', validate(z.object({ body: empty, params: idParams, query: z.object({}) })), listVersions);
router.get('/:id/versions/:versionId', validate(z.object({ body: empty, params: versionParams, query: z.object({}) })), getVersion);
router.post('/:id/versions', resumeFileUpload(), validate(z.object({ body: empty, params: idParams, query: z.object({}) })), createVersion);
router.delete('/:id/versions/:versionId', validate(z.object({ body: empty, params: versionParams, query: z.object({}) })), deleteVersion);
router.get('/:id/versions/:versionId/parsed', validate(z.object({ body: empty, params: versionParams, query: z.object({}) })), getParsed);
router.post('/:id/versions/:versionId/parsed/apply', validate(z.object({ body: apply, params: versionParams, query: z.object({}) })), applyParsed);
export const resumeRouter = router;
