import { getPrisma } from '../../db/prisma'; import { AppError } from '../../errors/app-error'; import { createAccessToken, createRefreshToken, hashPassword, hashRefreshToken, verifyAccessToken, verifyPassword } from './auth.crypto';
const publicUser={id:true,email:true,createdAt:true,updatedAt:true} as const;
export async function register(email:string,password:string){const db=getPrisma();const exists=await db.user.findUnique({where:{email}});if(exists)throw new AppError('EMAIL_ALREADY_EXISTS',409,'An account with this email already exists');const user=await db.user.create({data:{email,passwordHash:await hashPassword(password),profile:{create:{}}},select:publicUser});const session=await createSession(user.id);return tokens(user,session.id,session.refreshToken);}
export async function login(email:string,password:string){const user=await getPrisma().user.findUnique({where:{email}});if(!user||!(await verifyPassword(user.passwordHash,password)))throw new AppError('INVALID_CREDENTIALS',401,'Invalid email or password');const session=await createSession(user.id);return tokens(user,session.id,session.refreshToken);}
async function createSession(userId:string){const refreshToken=createRefreshToken();const session=await getPrisma().session.create({data:{userId,refreshTokenHash:hashRefreshToken(refreshToken),expiresAt:new Date(Date.now()+1000*60*60*24*30)}});return {id:session.id,refreshToken};}
function tokens(user:{id:string,email:string},sessionId:string,refreshToken:string){return {user,accessToken:createAccessToken(user.id,sessionId),refreshToken};}
export async function logout(sessionId:string){const db=getPrisma();const session=await db.session.findUnique({where:{id:sessionId}});if(session&&!session.revokedAt)await db.session.update({where:{id:sessionId},data:{revokedAt:new Date()}});}
export async function authenticateAccessToken(token:string){try{const claims=verifyAccessToken(token);const session=await getPrisma().session.findUnique({where:{id:claims.sid}});if(!session||session.userId!==claims.sub||session.revokedAt||session.expiresAt<=new Date())throw new Error('revoked');return claims;}catch{throw new AppError('UNAUTHORIZED',401,'Authentication required');}}
export async function getMe(userId:string){return getPrisma().user.findUnique({where:{id:userId},select:{id:true,email:true,createdAt:true,updatedAt:true,profile:{include:{skills:{include:{skill:true}},experience:true,education:true,preferences:true}}}});}
