import { getPrisma } from '../../db/prisma'; import { AppError } from '../../errors/app-error'; import { calculateProfileCompletion } from './profile-completion';
async function profileId(userId:string){const p=await getPrisma().candidateProfile.findUnique({where:{userId},select:{id:true}});if(!p)throw new AppError('PROFILE_NOT_FOUND',404,'Candidate profile not found');return p.id;}
export async function getProfile(userId:string){const p=await getPrisma().candidateProfile.findUnique({where:{userId},include:{skills:{include:{skill:true}},experience:{orderBy:{startDate:'desc'}},education:{orderBy:{startDate:'desc'}},preferences:true}});if(!p)throw new AppError('PROFILE_NOT_FOUND',404,'Candidate profile not found');return {...p,completion:calculateProfileCompletion(p)};}
export async function updateProfile(userId:string,data:any){const id=await profileId(userId);await getPrisma().candidateProfile.update({where:{id},data});return getProfile(userId);}
export async function listExperience(userId:string){const id=await profileId(userId);return getPrisma().experience.findMany({where:{profileId:id},orderBy:{startDate:'desc'}});}
export async function createExperience(userId:string,data:any){const id=await profileId(userId);return getPrisma().experience.create({data:{...data,profileId:id}});}
export async function updateExperience(userId:string,itemId:string,data:any){const id=await profileId(userId);const result=await getPrisma().experience.updateMany({where:{id:itemId,profileId:id},data});if(!result.count)throw new AppError('RESOURCE_NOT_FOUND',404,'Experience not found');return getPrisma().experience.findUnique({where:{id:itemId}});}
export async function deleteExperience(userId:string,itemId:string){const id=await profileId(userId);const result=await getPrisma().experience.deleteMany({where:{id:itemId,profileId:id}});if(!result.count)throw new AppError('RESOURCE_NOT_FOUND',404,'Experience not found');}
export async function listEducation(userId:string){const id=await profileId(userId);return getPrisma().education.findMany({where:{profileId:id},orderBy:{startDate:'desc'}});}
export async function createEducation(userId:string,data:any){const id=await profileId(userId);return getPrisma().education.create({data:{...data,profileId:id}});}
export async function updateEducation(userId:string,itemId:string,data:any){const id=await profileId(userId);const result=await getPrisma().education.updateMany({where:{id:itemId,profileId:id},data});if(!result.count)throw new AppError('RESOURCE_NOT_FOUND',404,'Education not found');return getPrisma().education.findUnique({where:{id:itemId}});}
export async function deleteEducation(userId:string,itemId:string){const id=await profileId(userId);const result=await getPrisma().education.deleteMany({where:{id:itemId,profileId:id}});if(!result.count)throw new AppError('RESOURCE_NOT_FOUND',404,'Education not found');}
export async function listSkills(userId:string){const id=await profileId(userId);return getPrisma().candidateSkill.findMany({where:{profileId:id},include:{skill:true},orderBy:{createdAt:'asc'}});}
export async function addSkill(userId:string,name:string,proficiency?:number|null){const profile=await profileId(userId);const normalized=name.trim().toLowerCase();const skill=await getPrisma().skill.upsert({where:{name:normalized},update:{},create:{name:normalized}});try{return await getPrisma().candidateSkill.create({data:{profileId:profile,skillId:skill.id,proficiency:proficiency??null},include:{skill:true}});}catch{throw new AppError('SKILL_ALREADY_EXISTS',409,'Skill is already associated with this profile');}}
export async function updateSkill(userId:string,itemId:string,data:any){const profile=await profileId(userId);const result=await getPrisma().candidateSkill.updateMany({where:{id:itemId,profileId:profile},data});if(!result.count)throw new AppError('RESOURCE_NOT_FOUND',404,'Skill not found');return getPrisma().candidateSkill.findUnique({where:{id:itemId},include:{skill:true}});}
export async function deleteSkill(userId:string,itemId:string){const profile=await profileId(userId);const result=await getPrisma().candidateSkill.deleteMany({where:{id:itemId,profileId:profile}});if(!result.count)throw new AppError('RESOURCE_NOT_FOUND',404,'Skill not found');}
export async function getPreferences(userId:string){const profile=await profileId(userId);return getPrisma().candidatePreference.findUnique({where:{profileId:profile}});}
export async function updatePreferences(userId:string,data:any){const profile=await profileId(userId);if(data.minSalary!=null&&data.maxSalary!=null&&data.minSalary>data.maxSalary)throw new AppError('INVALID_PREFERENCES',400,'Minimum salary cannot exceed maximum salary');return getPrisma().candidatePreference.upsert({where:{profileId:profile},create:{profileId:profile,...data},update:data});}
